### ISSUE TITLE
Not loading in Sinatra

### ISSUE THREAD

**Issue by HoneyryderChuck** [hassox/dm-polymorphic#3]
Hi,

I'm trying to bundle this gem with data mapper in my sinatra app, but somehow it cannot be loaded. I have them defined like this in my gemfile:

<pre>
<code>
gem "data_mapper",              '1.2.0'
gem "dm-mysql-adapter",         '1.2.0'
gem "dm-polymorphic",           '0.10.2'
</code>
</pre>

and I'm getting the following backtrace:

<pre><code>
/Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/dm-polymorphic-0.10.2/lib/dm-polymorphic.rb:46:in `<top (required)>': undefined method `/' for #<Pathname:0x00000104468c50> (NoMethodError)
    from /Users/tiagocardoso/Projects/rightclearing-api/app.rb:5:in `require'
    from /Users/tiagocardoso/Projects/rightclearing-api/app.rb:5:in `<top (required)>'
    from /Users/tiagocardoso/Projects/rightclearing-api/spec/spec_helper.rb:3:in `require'
    from /Users/tiagocardoso/Projects/rightclearing-api/spec/spec_helper.rb:3:in `<top (required)>'
    from /Users/tiagocardoso/Projects/rightclearing-api/spec/models/authorization_spec.rb:2:in `require'
    from /Users/tiagocardoso/Projects/rightclearing-api/spec/models/authorization_spec.rb:2:in `<top (required)>'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `block in load_spec_files'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `map'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load_spec_files'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
    from /Users/tiagocardoso/Projects/rightclearing-api/bundled_gems/ruby/1.9.1/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
</code></pre>

Should this work under Sinatra?

**Comment by HoneyryderChuck** [comment]
Now that I have looked further into this, it looks like ur gem is outdated concerning the data mapper version. Is it so?
